##################
# app.yaml
runtime: python310
instance_class: F3
entrypoint: gunicorn -b :$PORT 'src.__init__:app' --timeout 600
automatic_scaling:
  target_cpu_utilization: 0.8
  min_instances: 0
  max_instances: 5
##======================

