###############
# Swagger API swagger.yaml#
# https://editor.swagger.io/
openapi: '3.0.0'
info:
  title: ProductExplorer
  version: '1.0'
  description: A sample API for product investigation.

paths:
  /start_investigation:
    post:
      operationId: src.main.api_start_investigation
      summary: Initiates a new investigation.
      description: |
        This endpoint initiates a new investigation based on the provided user ID and list of ASINs.
      tags:
        - Start Investigation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  description: The ID of the user.
                asins:
                  type: array
                  items:
                    type: string
                  description: List of ASINs for the investigation.
      responses:
        '200':
          description: Investigation started successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  user_id:
                    type: string
                  asins:
                    type: array
                    items:
                      type: string
                  status:
                    type: string
                  start_timestamp:
                    type: string
        '400':
          description: Bad request. Missing or invalid parameters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error or processing error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    
  /run_data_acquisition:
    post:
      operationId: src.main.api_run_data_acquisition
      summary: Initiates data acquisition.
      description: |
        This endpoint initiates data acquisition based on the provided list of ASINs.
      tags:
        - Data Acquisition
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                asins:
                  type: array
                  items:
                    type: string
                  description: List of ASINs for data acquisition.
      responses:
        '200':
          description: Data acquisition completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad request. Missing or invalid parameters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error or processing error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string


  /run_products_investigation:
    post:
      operationId: src.main.api_run_products_investigation
      summary: Initiates a product investigation.
      description: |
        This endpoint initiates a product investigation based on the provided investigation ID and credential path.
      tags:
        - Investigation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                investigation_id:
                  type: string
                  description: The ID of the investigation.

      responses:
        '200':
          description: Investigation completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad request. Missing or invalid parameters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error or processing error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /run_reviews_investigation:
    post:
      operationId: src.main.api_run_reviews_investigation
      summary: Initiates a reviews investigation.
      description: |
        This endpoint initiates a reviews investigation based on the provided investigation ID and credential path.
      tags:
        - Investigation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                investigation_id:
                  type: string
                  description: The ID of the investigation.
      responses:
        '200':
          description: Reviews investigation completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad request. Missing or invalid parameters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error or processing error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /run_end_to_end_investigation:
    post:
      operationId: src.main.api_run_end_to_end_investigation
      summary: Initiates an end-to-end investigation.
      description: |
        This endpoint initiates an end-to-end investigation based on the provided user ID and list of ASINs.
      tags:
        - Investigation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  description: The ID of the user.
                asins:
                  type: array
                  items:
                    type: string
                  description: List of ASINs for the investigation.
      responses:
        '200':
          description: End-to-end investigation completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad request. Missing or invalid parameters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error or processing error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /create_user:
    post:
      operationId: src.main.api_create_user
      summary: Create a new user.
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the user.
                email:
                  type: string
                  description: The email of the user.
      responses:
        '201':
          description: User created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /get_user:
    get:
      operationId: src.main.api_get_user
      summary: Retrieve user data.
      tags:
        - User
      parameters:
        - name: userId
          in: query
          description: The ID of the user to retrieve.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User data retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
        '404':
          description: User not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /subscribe_user:
    post:
      operationId: src.main.api_subscribe_user
      summary: Subscribe a user to a package.
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: The ID of the user.
                package:
                  type: string
                  description: The package to subscribe to.
      responses:
        '201':
          description: Subscription successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  userId:
                    type: string
                  package:
                    type: string
                  startDate:
                    type: string
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /log_payment:
    post:
      operationId: src.main.api_log_payment
      summary: Log a payment.
      tags:
        - Payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                amount:
                  type: number
                timestamp:
                  type: string
      responses:
        '201':
          description: Payment logged successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  paymentId:
                    type: string
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /subscribe_user_to_package:
    post:
      operationId: src.main.api_subscribe_user_to_package
      summary: Subscribe a user to a package and update their investigation count.
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                package:
                  type: string
                startDate:
                  type: string
                paymentIntentId:
                  type: string
      responses:
        '200':
          description: Subscription successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

                    
#====================