##################
# app.yaml
runtime: python310
instance_class: F2
entrypoint: gunicorn -b :$PORT main:connex_app
automatic_scaling:
  target_cpu_utilization: 65
  min_instances: 0
  max_instances: 10
###################